### ISSUE TITLE
not working after 0.92

### ISSUE THREAD

**Issue by fernandex00** [tenly2000/HomeAssistant-Places#4]
just update to hassio 0.92, and the component stops working, add the manifiest.json but it its not working anymore

**Comment by elRadix** [comment]
I get the following error


```
 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform Places
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/Places/sensor.py", line 312, in setup_platform
    add_devices([Places(hass, devicetracker_id, name, api_key, options, home_zone, map_provider, map_zoom)])
  File "/home/homeassistant/.homeassistant/custom_components/Places/sensor.py", line 332, in __init__
    self._entity_picture = hass.states.get(devicetracker_id).attributes.get('entity_picture')
AttributeError: 'NoneType' object has no attribute 'attributes'
2019-04-25 19:10:12 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform Places
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/Places/sensor.py", line 312, in setup_platform
    add_devices([Places(hass, devicetracker_id, name, api_key, options, home_zone, map_provider, map_zoom)])
  File "/home/homeassistant/.homeassistant/custom_components/Places/sensor.py", line 332, in __init__
    self._entity_picture = hass.states.get(devicetracker_id).attributes.get('entity_picture')
AttributeError: 'NoneType' object has no attribute 'attributes
```

**Comment by fernandex00** [comment]
this is the error in the log

Error while setting up platform places

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/places/sensor.py", line 297, in setup_platform
    add_devices([Places(hass, devicetracker_id, name, api_key, options, home_zone, map_provider, map_zoom)])
  File "/config/custom_components/places/sensor.py", line 317, in __init__
    self._entity_picture = hass.states.get(devicetracker_id).attributes.get('entity_picture')
AttributeError: 'NoneType' object has no attribute 'attributes'
```

**Comment by nelbs** [comment]
Same error here :(

**Comment by fernandex00** [comment]
> Same error here :(

hope the dev, read this an fix it, this is a great component

**Comment by nelbs** [comment]
Adding the dependencies in the manifest.json fixed it.

```
{
  "domain": "Sensor",
  "name": "Reverse Geocode Sensor",
  "documentation": "https://github.com/tenly2000/HomeAssistant-Places",
  "requirements": [],
  "dependencies": ["zone","device_tracker"],
  "codeowners": []
}
```

**Comment by fernandex00** [comment]
thank you, that do it, close this now
